name: Deploy master
on:
  push:
    branches: [ main ]

inputs:
  DEPLOY-PACKAGE-NAME: "Application-${{ github.sha }}.zip"   
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
   
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~\.nuget\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**\packages.lock.json') }}    

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:DebugType=None
        
    - name: Dotnet publish
      run: dotnet publish -o site

    - name: Generate deployment package
      run: |
        cd site
        zip -r ${{ inputs.DEPLOY-PACKAGE-NAME }} . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: MySampleApp
        environment_name: Mysampleapp-env
        version_label: "Ver-${{ github.sha }}"
        region: us-east-1
        deployment_package: "${{ inputs.DEPLOY-PACKAGE-NAME }}.zip"
