name: Deploy master
on:
  push:
    branches: [ main ]

env:
  DEPLOY-PACKAGE-NAME: "Application-${{ github.sha }}.zip"   
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
   
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~\.nuget\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**\packages.lock.json') }}    

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:DebugType=None
        
    - name: Dotnet publish 
      run: dotnet publish -o bundle

    - name: Generate deployment package
      uses: papeloto/action-zip@v1
      with:
        files: bundle/
        recursive: true
        dest: site.zip
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}\site.zip
    

